name: IncBossesAbility_Actions
version: '${project.version}'
main: ru.incrementstudio.incbosses.abilities.incbossesability_actions.Main
api-version: '1.16'
author: IncrementStudio++
description: Способность для плагина IncBosses, добавляющая возможность выполнения различных действий при спавне, смерти или смене фаз босса!
website: incrementstudio.ru
softdepend:
  - PlaceholderAPI